# nixpacks.toml (v3 - Corrected Syntax)

# Phase 1: Setup - Install system-level dependencies AND the Python interpreter
[phases.setup]
nixPkgs = [
    # Explicitly install a Python 3.11 environment. This makes the `python3` command available.
    "python311",
    # System dependencies for Playwright browsers
    "nodejs"
]

# Phase 2: Build - Install Python packages and then install Playwright browsers
[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    # This command installs the necessary browser binaries AND their OS dependencies
    "playwright install --with-deps"
]

# Phase 3: Start - The command to run your bot
[start]
# Use "python3" to be explicit. The "-u" flag ensures unbuffered output for logs.
cmd = "python3 -u main.py"
